#!/bin/bash

GEM_CONFIG_FILE=${GEM_CONFIG_FILE:-"gemrc"}

set -u
set -x

bundle install --local --verbose

cd vendor/cache
gem install --config-file $GEM_CONFIG_FILE ./*.gem

cd gem-compare-*
gem build --config-file $GEM_CONFIG_FILE gem-compare.gemspec
gem install --config-file $GEM_CONFIG_FILE ./gem-compare-*.gem
