name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      pr:
        description: "The number of the pull request to comment in"
        required: false
        type: number


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: rake

      - uses: ./
        with:
          pr_diff: test/fixtures/sentry.diff
          pr_number: ${{ inputs.pr || 2 }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
