name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      gemrc:
        description: 'Use "gemrc" for non-debug config'
        required: false
        type: string
      pr_title:
        description: 'String in the format "Bump <GEM> from <VERSION_X> to <VERSION_Y>"'
        required: false
        type: string
      pr_number:
        description: 'The number of the pull request to comment in'
        required: false
        type: number

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          pr_title: ${{ inputs.pr_number || 'Bump sequel from 5.57.0 to 5.58.0' }}
          pr_number: ${{ inputs.pr_number || 1 }}
          gemrc: ${{ inputs.gemrc || 'gemrc_debug' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
